services:
  db:
    image: postgis/postgis:17-3.5
    container_name: krit_gis_db
    environment:
      POSTGRES_DB: krit_gis
      POSTGRES_USER: geodock_admin
      POSTGRES_PASSWORD: geodock_admin
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5440:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U geodock_admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
