services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: krit_gis_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5440:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - krit_gis_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: krit_gis_backend
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            python manage.py createsuperuser --noinput --username ${DJANGO_SUPERUSER_USERNAME} --email ${DJANGO_SUPERUSER_EMAIL} &&
            python manage.py loaddata attributes_company attributes_construction_type attributes_phase attributes_status attributes_surface storage_preference file_type_categories projects flags &&
            gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/static
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEFAULT_SRID=${DEFAULT_SRID}
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - NEXTCLOUD_PUBLIC_URL=${NEXTCLOUD_PUBLIC_URL}
      - NEXTCLOUD_FILEUPLOADER_USERNAME=${NEXTCLOUD_FILEUPLOADER_USERNAME}
      - NEXTCLOUD_FILEUPLOADER_PASSWORD=${NEXTCLOUD_FILEUPLOADER_PASSWORD}
      - NEXTCLOUD_BASE_PATH=${NEXTCLOUD_BASE_PATH}
      - NEXTCLOUD_VERIFY_SSL=${NEXTCLOUD_VERIFY_SSL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - krit_gis_network

  geoserver:
    image: kartoza/geoserver:latest
    container_name: krit_gis_geoserver
    restart: unless-stopped
    ports:
      - "${GEOSERVER_PORT:-8081}:8080"
    expose:
      - "8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - PROXY_BASE_URL=https://geoserver.localhost/geoserver
      - SKIP_DEMO_DATA=true
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS="ogcapi-features"
      - GEOSERVER_CSRF_DISABLED=true
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/" || exit 1
      interval: 1m
      timeout: 20s
      retries: 3
    networks:
      - krit_gis_network

  nextcloud:
    image: nextcloud:latest
    container_name: krit_nextcloud
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT:-8080}:80"
    expose:
      - "80"
    volumes:
      - ./nextcloud/data/nextcloud:/var/www/html
      - ./nextcloud/data/apps:/var/www/html/custom_apps
      - ./nextcloud/data/config:/var/www/html/config
      - ./nextcloud/data/files:/var/www/html/data:rw
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${NEXTCLOUD_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - NEXTCLOUD_OVERWRITEHOST=${NEXTCLOUD_TRUSTED_DOMAINS:-cloud.localhost}
      - NEXTCLOUD_OVERWRITEPROTOCOL=https
    depends_on:
      db:
        condition: service_healthy
    networks:
      - krit_gis_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: krit_gis_frontend
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - ORIGIN=https://app.localhost
    networks:
      - krit_gis_network
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: krit_gis_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static
    expose:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
      - nextcloud
      - frontend
    networks:
      - krit_gis_network

  caddy:
    image: caddy:2
    container_name: krit_gis_caddy
    restart: unless-stopped
    ports:
      - "${CADDY_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/certificates:/data/caddy/certificates
    environment:
      - XDG_DATA_HOME=/data
      - XDG_CONFIG_HOME=/config
    cap_add:
      - NET_ADMIN
    depends_on:
      - nginx
      - nextcloud
      - frontend
    networks:
      - krit_gis_network

volumes:
  caddy_data:
  caddy_config:
  static_volume: {}
  geoserver_data: {}

networks:
  krit_gis_network:
    name: krit_gis_network
    driver: bridge
